# Generated by Django 6.0.2 on 2026-02-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_Id', models.PositiveIntegerField()),
                ('Emp_name', models.CharField(max_length=30)),
                ('Emp_email', models.EmailField(max_length=254, unique=True)),
                ('Emp_position', models.CharField(max_length=50)),
                ('Emp_phone', models.CharField(max_length=15)),
            ],
        ),
    ]
